### ISSUE TITLE
tweepub image not compatible with all the networks/dns plugins

### ISSUE THREAD

**Issue by ashaposhnikov** [Aptomi/aptomi#195]
AFAIS tweepub image based on alpine which have a lot of issues with dns resolving in different configurations and/or network types (CNIs). I've tried it with regular Flannel CNI + K8S 1.8.3 and it looks like alpine doesn't handle ndots option well and not able to resolve anything. It may or may no be a correct behavior but AFAIK everybody trying to resolve FQDN first and only after that try to use local domain but alpine probably doing that in reversed way so, starting from non-existent and fails.

**Comment by AleksandrNull** [comment]
/ # cat /etc/resolv.conf 
nameserver 10.96.0.10
search default.svc.cluster.local svc.cluster.local cluster.local local
options ndots:5
/ # ping ya.ru
ping: bad address 'ya.ru'
/ # vi /etc/resolv.conf 
---removing options ndots:5-----
/ # ping ya.ru
PING ya.ru (87.250.250.242): 56 data bytes
64 bytes from 87.250.250.242: seq=0 ttl=52 time=25.066 ms

**Comment by Frostman** [comment]
Done. Image switched to Debian Jessie.
