### ISSUE TITLE
Do not allow to change a cluster via API

### ISSUE THREAD

**Issue by Frostman** [Aptomi/aptomi#253]
Modification of clusters can lead to problems:
- if it has running component instances on it, then the underlying cluster object would be changed but components will still be running on the old cluster

So we should not allow to change them after they have been uploaded. In order to update, you must delete a cluster first.

**Comment by ralekseenkov** [comment]
It was very hard to check the condition "if a cluster changed" && "it has running component instances on it", so we will just not allow modifications of clusters all together
