### ISSUE TITLE
Make system/release doesn't work correctly with double-digit versions

### ISSUE THREAD

**Issue by ralekseenkov** [Aptomi/aptomi#255]
I'm building from master:
```
# ./aptomi version
Git Version           	Git Commit                              	Build Date
dev-v0.1.9-81-geb7f5de	eb7f5de18a8d6a52e8f9d49c45564ba5c3d3ee8e	2018-02-22T21:06:36Z
```

It says 0.1.9, even though it should be 0.1.10?

```
# git describe --tags --long --dirty
v0.1.9-81-geb7f5de
```

I think we need to use something along the lines of:
```
# git tag -l --sort=v:refname
or 
# git tag -l --sort=-v:refname
```

**Comment by Frostman** [comment]
Nope, I've just checked it on a fresh git cloned repo, so, you just have local tags other then upstream tags. Run ```git fetch --tags --force``` to refresh your local tags.
