### ISSUE TITLE
Unclear error messages when validating policy

### ISSUE THREAD

**Issue by ralekseenkov** [Aptomi/aptomi#285]
E.g. 
```
FATA[0000] Error while applying policy: server error: Updated policy is invalid: Policy.Namespace[social].Services[twitter_stats].Components[1].Code.Params: Params must be a valid text template map (all nested text templates must be valid)
```

**Comment by Frostman** [comment]
Please, describe more the case and how it's unclear?

**Comment by ralekseenkov** [comment]
If you made a mistake in policy YAML files, it's very hard to figure out what's wrong... because we often don't print the underlying error message. In this particular case it doesn't return an underlying error from text/template, so you don't know what's wrong with your template.

Go doesn't have a good library that suits our needs:
- `go-playground/validator` (the one that we use right now) doesn't allow to return custom error messages for Field-level validators
- `asaskevich/govalidator` doesn't work well with nested structs
