### ISSUE TITLE
Automatic verification of demo scenario

### ISSUE THREAD

**Issue by Frostman** [Aptomi/aptomi#83]
In k8s

**Comment by ralekseenkov** [comment]
This is pretty much the script. Just need to add waits & checks:

aptomictl -u Sam policy show

aptomictl policy apply --username Sam -f examples/03-twitter-analytics/policy/Sam

aptomictl policy apply --username Frank -f examples/03-twitter-analytics/policy/Frank

aptomictl policy apply --username John -f examples/03-twitter-analytics/policy/John

aptomictl policy apply --username John -f examples/03-twitter-analytics/policy/john-prod-ts.yaml

aptomictl policy apply --username Alice -f examples/03-twitter-analytics/policy/alice-stage-ts.yaml

aptomictl policy apply --username Bob -f examples/03-twitter-analytics/policy/bob-stage-ts.yaml

aptomictl policy delete --username Alice -f examples/03-twitter-analytics/policy/alice-stage-ts.yaml

sed -e 's/demo-v61/demo-v62/g' examples/03-twitter-analytics/policy/john-prod-ts.yaml > examples/03-twitter-analytics/policy/john-prod-ts-changed.yaml

aptomictl policy apply --username John -f examples/03-twitter-analytics/policy/john-prod-ts-changed.yaml

aptomictl policy apply --username Carol -f examples/03-twitter-analytics/policy/carol-stage-ts.yaml
